chore: CI github actions cleanup (#965)
* auction: fix test build errors

* chore: documenting puff data fields reasoning

* utils: exposing puffed_out_string method

* test: fix create_metadata_account success

- expecting name, symbol and uri to be puffed out

* utils: using puffed_out_string for puff_out_data_fields

* test: wrapping in mods named after file

- supports running test files in isolation, i.e.
  `cargo test-bpf update_primary_sale_happened_via_token`
- improves out put of tests failing vs. passing, i.e.
  `'update_primary_sale_happened_via_token::success' panicked at ..`

* test: fixing update* tests expecting puffed strings

* chore: adding note to mint tests about token-vault dependency

* chore: adding rust format

- adapted to current formatting especially line width
- enforcing ordering and grouping of imports since at this point they
  are all over the place
- the exact specs are up for discussion and we can reformat after that

* style: formatting tests to added rust fmt

* style: formatting code to match rustfmt

- this resulted mainly in an improved organization of imports

* test: util puff functions and noted input requirements

* test: marking tests bpf where needed

* ci: setting up deps and tests

- deps installs via actions
  - install solana
  - rust install
  - adding linux build deps
- tests using those actions via main

* ci: adding token vault test action with implicit deps

- github actions are not smart enough to realize that a `- use` was
  already handled and runs it each time it sees it
- making it implicit for the action avoids that
- we expect the steps using an action to supply the `- use` statements
  instead
- first intents at adding caching

* ci: making actions configurable

* ci: caching per test run

- caching with same id for each rust install/build does not work since
  the produced artifacts in each case are slightly different

* ci: run test before test-bpf

* ci: running tests single threaded for easier to parse output

* ci: enabling js lint and tests

* ci: scoping build-and-test to ./rust changes

* chore: running actions on PRs and master changes only

* ci: fixing path filters